### ISSUE TITLE
Please help me to work with html forms

### ISSUE THREAD

**Issue by kwhandy** [TonyBrobston/jpegasus#165]
This package is great but can you tell me how to replace html image input data form with the compressed image generated from this package? I really sorry to open issue:(

**Comment by TonyBrobston** [comment]
@kwhandy Have a look at my example repo, specifically this JavaScript: https://github.com/TonyBrobston/jpegasus-demo/blob/b636a4a4cf9ff7ad14f64fcf0ff9747e2a57500e/src/js/main.js#L56

If that does not help, can you provide me a link to your repo or a codesandbox of what you're trying to do?

**Comment by TonyBrobston** [comment]
@kwhandy I'm going to close this. Let me know if you need anything else.

**Comment by kwhandy** [comment]
Hi! Sorry for really slow response. I just want to use normal html form but with attaching jpegasus code, I can replace choosen file inside the file input(just one file input) right after I choose one jpg/png from my pc. Here is my html: https://codesandbox.io/s/vigilant-hofstadter-e1pn4?file=/index.html. Or maybe you have simpler suggestion for this? I really appreciate your help

**Comment by TonyBrobston** [comment]
@kwhandy I started by trying to modify your codesandbox, but then I realized I'm not really sure what you're trying to do. I image you're pulling a image into an input field, then wanting to compress that image, then call something to upload the compressed image; but because the last piece isn't there (uploading an image), I don't know what to do with the compressed image.

So instead I decided to pull my `jpegasus-demo` code into a codesandbox and implement using `parcel` as you are. `parcel` seems pretty neat. I think the biggest thing that I had to overcome, was figuring out how to get my javascript functions to be available to my html. With a bit of googling I found this post:
https://stackoverflow.com/questions/57602686/javascript-function-wont-trigger-when-called-in-html-file-during-parcel-build

Once I was able to get my javascript functions to be available, everything else became much simpler.

Take a look at my sandbox and see if that helps with what you need:
https://codesandbox.io/s/lively-architecture-gud6w
