### ISSUE TITLE
PNG output?

### ISSUE THREAD

**Issue by joonaspaakko** [TonyBrobston/jpegasus#180]
PNG transparency is discarded

What I'm getting:
![jpegasus-star-example](https://user-images.githubusercontent.com/1164476/95973805-cad8a180-0e1c-11eb-84b6-8dc5a81175fa.png)

Original file:
![star-icon](https://user-images.githubusercontent.com/1164476/95973837-d4620980-0e1c-11eb-9f1c-0c8dcbe008bf.png)

**Comment by joonaspaakko** [comment]
**My bad...** I read that it supports png, but I guess I never got further than that in the readme, because I didn't realize it outputs jpegs. Any chance it could output png files?

**Comment by TonyBrobston** [comment]
@joonaspaakko Thank you for reporting this!

I did a bit of experimenting and it seems possible to fix this.

I swapped `image/jpeg` for `image/png` on these two lines and was able to produce a transparent png:
https://github.com/TonyBrobston/jpegasus/blob/772b15550b350d0d549fac6608ba7b2ef1936b2c/src/services/qualityService.ts#L6
https://github.com/TonyBrobston/jpegasus/blob/772b15550b350d0d549fac6608ba7b2ef1936b2c/src/services/qualityService.ts#L9

I need to doing a bit more experimenting to determine the implementation. This will definitely be some sort of option. I'm thinking either `preserveOriginalImageType` which defaults to `false` and uses `image/jpeg`; when set to `true` it will use the original image type. Another approach could be to have an option of `alwaysReturnType`, which you could input one from a list of choices: `image/jpeg`, `image/png`, etc.

I'll mess with this a bit more shortly. I'm wondering things like, if `alwaysReturnType`: `image/png`; what happens if I compress an `image/jpeg`? So a bit more experimenting to do. I lean towards `preserveOriginalImageType`. If I can make this decision shortly I'll likely have a release in the next day or two.

**Comment by TonyBrobston** [comment]
Actually, while this seems to not break anything, I am not seeing the compress file size change when changing input options. This seems to imply that this form of image compression may not support the output of anything other than jpeg. I'll continue looking.

**Comment by joonaspaakko** [comment]
Sounds good to me 👍

**Comment by TonyBrobston** [comment]
Looking a bit into the idea of changing the jpeg matte color, that seems very viable. I was able to add:
```
context.fillStyle = '#FFFFFF';
context.fillRect(0, 0, scaledWidth, scaledHeight)
```
Right above this line:
https://github.com/TonyBrobston/jpegasus/blob/772b15550b350d0d549fac6608ba7b2ef1936b2c/src/services/canvasService.ts#L64

This seems to swap black for white effectively. I'm going to experiment a bit more.

**Comment by TonyBrobston** [comment]
Alright, so I think I have done enough experimenting/research to determine that compression isn't possible while retaining transparency. If we convert the `image/png` to `image/jpeg` in order to compress, we lose transparency. (Maybe there's something that can be done to convert a `image/jpeg` to an `image/png` and say like "replace a certain color with transparency", but that seems error prone if it's even a thing.)

The documentation for `quality` here:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
says: "A Number between 0 and 1 indicating the image quality to use for image formats that use lossy compression such as image/jpeg and image/webp."
This explains why the compressed image size wouldn't change on an `image/png` when I changed `quality`. So, if we do support transparency, we can't compress, which seems counterproductive.

I think the answer is to set the `fillStyle` to white. Seems like a reasonable stop-gap. I also think the main use of this package is to compress large images taken by modern cell phones, before uploading somewhere. It seems like that scenario will never produce an `image/png`. However, I realize everyone uses tools for different reasons, which is why I wanted to see if I could support transparancy.

Does this approach help you @joonaspaakko ? If I set the background/matte color to white, will that be sufficient solution for your needs?

**Comment by joonaspaakko** [comment]
Yea, I don't want to steer the project in the wrong direction, but at this point I'd personally be happy if I could just resize pngs without any compression, if that's doable.

Currently I'm just detecting png files and passing them forward without pushing them through jpegasus.

----

If there was an option to set the jpeg matte color, I'd need to be able to set the color myself, if possible. I would imagine white would work for many use cases, more so than black, but similar to black, it won't always work.

**Comment by TonyBrobston** [comment]
@joonaspaakko I'm opening to trying to solve problems. The feedback definitely helps.

I could definitely add a `preserveFileType` option and note that compression breaks when the file type is not `image/jpeg`; this should still allow height/width and scaling to be used, which will still effect compressed image size. Also `pngTransparencyFillColor` could be exposed as an option and defaulted to `#FFF`.

What are your thoughts on that?

**Comment by joonaspaakko** [comment]
Sounds good.

**Comment by TonyBrobston** [comment]
`transparencyFillColor`: https://github.com/TonyBrobston/jpegasus/pull/181

This is really `fillStyle` under the hood, so this will support anything that supports, it's a straight passthrough. Defaults to `'#FFF'`.

**Comment by TonyBrobston** [comment]
`https://github.com/TonyBrobston/jpegasus/pull/184`: https://github.com/TonyBrobston/jpegasus/pull/184

**Comment by TonyBrobston** [comment]
@joonaspaakko I tagged a release, which also does a npm deploy. https://github.com/TonyBrobston/jpegasus/releases/tag/1.16.0 This should be out there as soon as travis-ci finishes a build/deploy. I will update my demo site shortly after that.

**Comment by TonyBrobston** [comment]
Also I updated https://tonybrobston.github.io/jpegasus-demo/ so if you want to experiment with how these two new options work, you can.
