### ISSUE TITLE
Add optional face blur

### ISSUE THREAD

**Issue by lounsbrough** [TonyBrobston/jpegasus#31]

**Comment by TonyBrobston** [comment]
May be possible with this: https://github.com/justadudewhohacks/face-api.js/blob/master/README.md

However it seems to me that this likely should be it's own package entirely. I'm wondering if I could use one package to detect where the face is and another to blur it; basically just one thin wrappers, wrapping two containers 🤩.

**Comment by TonyBrobston** [comment]
`face-api.js` seems promising, however I don't currently have time to investigate. I'm going to close this since I believe this work should be it's own package entirely. I picture another package that is simply a thin wrapper over the top of `face-api.js` and some tool that `blurs` sections of images given some coordinate hopefully provided by `face-api.js`.
